#!/usr/bin/env python
# encoding: utf-8

import ogr,os

infile = 'H:\\西安矢量数据及大范围影像\\全国矢量数据\\CHN_adm2.shp'
driver = ogr.GetDriverByName('ESRI Shapefile')
inds = ogr.Open(infile)
inlayer = inds.GetLayer()

insrs =inlayer.GetSpatialRef()
#print(insrs)

#创建输出文件
outfile = 'H:\\code_test\\centriod2point\\centroid.shp'
if os.path.exists(outfile):
    driver.DeleteDataSource(outfile)
outds = driver.CreateDataSource(outfile)

outlayer = outds.CreateLayer('Centroids_countries',srs = insrs,geom_type = ogr.wkbPoint)
#定义属性表
infeaturedefn = inlayer.GetLayerDefn()
fieldcount = infeaturedefn.GetFieldCount()
for i in range(fieldcount):
    outfielddefn = infeaturedefn.GetFieldDefn(i)
    outlayer.CreateField(outfielddefn)
#获取输出图层属性定义
outfeaturedefn = outlayer.GetLayerDefn()
#遍历要素，获取中心点，创建输出要素，写入几何点，写入字段值，写入图层
for i in range((inlayer.GetFeatureCount())):
    feat = inlayer.GetFeature(i)
    outfeat = ogr.Feature(outfeaturedefn)
    #写入字段值
    for j in range(outfeaturedefn.GetFieldCount()):
        outfeat.SetField(outfeaturedefn.GetFieldDefn(j).GetNameRef(), feat.GetField(j))
    #获取几何，提取中心点
    geom = feat.GetGeometryRef()
    centroids = geom.Centroid()
    outfeat.SetGeometry(centroids)
    #添加到图层
    outlayer.CreateFeature(outfeat)
    # feat = None
    # outfeat = None
inds = None
outds = None
