#!/usr/bin/env python
# encoding: utf-8

from osgeo import gdal, ogr, osr
import os, sys
import numpy as np
import pandas as pd

ogr.RegisterAll()


def field_standard(excel_path):
    data = pd.DataFrame(pd.read_excel(excel_path))
    field_standard = []
    for index in range(0, 21, 4):#视excel实际情况而定
        lc = data.loc[index].values.tolist()
        field_name = []
        for i in range(len(lc)):
            if lc[i] is not np.nan:
                field_name.append(lc[i].split('（')[0])
        field_standard.append((field_name))
    return field_standard

def get_condition(filepath,standard):
    name=[]
    shp_file = ogr.Open(filepath)
    layer = shp_file.GetLayer()
    layerDefn = layer.GetLayerDefn()
    field_count = layerDefn.GetFieldCount()
    for j in range(field_count):
        fieldName = layerDefn.GetFieldDefn(j).GetName()
        name.append(fieldName)
    count1=len(name)
    count2=len(standard)
    if sorted(name) == sorted(standard):
        condition=['属性字段检查合格，已经入库！']
    else:
        with_standard=[]
        without_standard=[]
        for n in name:
            if n in standard:
                with_standard.append(n)
            else:
                without_standard.append(n)
        c1=list(set(standard) - set(with_standard))
        condition=np.array((c1,without_standard))
    return condition



if __name__ == '__main__':
    excel_path='H:\\西安环保\\西安环保字段.xlsx'
    standard=field_standard(excel_path)
    field = ["涝池", "工地扬尘", "垃圾", "黑臭水体", "水源地", "火点"]

    filepath = 'G:\\西安环保\\扬尘\\一期矢量\\扬尘点2020年1月份.shp'
    filename=os.path.basename(filepath).split('.')[0]
    instr = "工地扬尘"
    p=field.index(instr)
    condition = get_condition(filepath, standard[p])

    if len(condition)==1:
        output={filename:str(condition)}
    else:
        output={'文件名': filename,
                '属性字段缺少': str(condition[0]),
                '属性字段多出': str(condition[1]),
                '修改意见': '缺少字段需要添加，多出字段需要删除'}
    print(output)
